# Generated by Django 3.0.7 on 2021-03-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210301_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(max_length=255),
        ),
    ]
